#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   stevenlu         StevenLu's Popular Movies   #
#          #   anidb            AniDB Popular               #
#          #   pirated          Top 10 Pirated Movies       #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          radarr_add_missing_key:                          #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

# external_templates:
#   repo: PMM/templates
#   template_variables:
#     collection_section: "04"

collections:
  Netflix Anime Shows:
    mdblist_list: https://mdblist.com/lists/ramshackles/netflix-anime-60
    summary: Anime Shows on Netflix with rating above 60, no bollywood or documentary.
    sync_mode: sync
    collection_order: alpha
    build_collection: false
    url_poster: https://github.com/meisnate12/Plex-Meta-Manager-Images/raw/master/network/Netflix.jpg
    allowed_library_types: show
    sonarr_add_missing: true
    sonarr_tag: anime, pmm_nfanime
    sonarr_folder: /data/media/tv/anime
    sonarr_series: anime

  Netflix Movies:
    mdblist_list: https://mdblist.com/lists/ramshackles/netflix-movies-60
    summary: Movies on Netflix with rating above 60, no bollywood or documentary..
    sync_mode: sync
    collection_order: alpha
    build_collection: false
    url_poster: https://github.com/meisnate12/Plex-Meta-Manager-Images/raw/master/network/Netflix.jpg
    allowed_library_types: movie
    # radarr_add_missing: true
    # radarr_tag: pmm_nfmovie