#############################################################
#                  Other Chart Collections                  #
#         Created by Yozora, Bullmoose20, & Sohjiro         #
#############################################################
#  Call this from your config.yml (Movie or Show)           #
#  If nothing is specified these are the defaults           #
#                                                           #
#    metadata_path:                                         #
#      - git: PMM/chart/other                               #
#        template_variables:                                #
#          # Sets the collection mode of the collection     #
#          collection_mode:                                 #
#          # Sets the value at the start of the sort title  #
#          collection_section: "01"                         #
#                                                           #
#          # For each collection use the "key" to set       #
#          # the options.                                   #
#          # Available collections                          #
#          #   KEY              COLLECTION                  #
#          #   stevenlu         StevenLu's Popular Movies   #
#          #   anidb            AniDB Popular               #
#          #   pirated          Top 10 Pirated Movies       #
#                                                           #
#          # Available options. Replace "key" with the      #
#          # desired collection's key from the chart above. #
#                                                           #
#          # Turn the collection on/off                     #
#          use_key: true                                    #
#          # Determines collection order in its section     #
#          order_key:                                       #
#          # Set visible_library for the collection         #
#          visible_library_key:                             #
#          # Set visible_home for the collection            #
#          visible_home_key:                                #
#          # Set visible_shared for the collection          #
#          visible_shared_key:                              #
#          # Adds missing from the collection to radarr     #
#          radarr_add_missing_key:                          #
#          # Adds missing from the collection to sonarr     #
#          radarr_add_missing_key:                          #
#          # Radarr Tag for added missing                   #
#          radarr_tag_key:                                  #
#          # Sonarr Tag for added missing                   #
#          sonarr_tag_key:                                  #
#          # Radarr Tag for existing items                  #
#          item_radarr_tag_key:                             #
#          # Sonarr Tag for existing items                  #
#          item_sonarr_tag_key:                             #
#############################################################

# external_templates:
#   repo: PMM/templates
#   template_variables:
#     collection_section: "01"

collections:
#   RT Latest Certified Fresh:
#     mdblist_list: https://mdblist.com/lists/linaspurinis/latest-certified-fresh-releases
#     summary: Latest Certified Fresh releases from Rotten Tomatoes
#     template:
#       - name: customsync
#       - name: chart_shared
#         key: rtlatestfresh
#         check_library: movie

  # RT Certified Fresh:
  #   mdblist_list: https://mdblist.com/lists/linaspurinis/certified-fresh
  #   summary: Certified Fresh releases from Rotten Tomatoes
  #   template:
  #     - name: customsync
  #     - name: chart_shared
  #       key: rtfresh
  #       check_library: movie

  RT Latest Certified Fresh:
    mdblist_list: https://mdblist.com/lists/linaspurinis/latest-certified-fresh-releases
    summary: Latest Certified Fresh releases from Rotten Tomatoes
    sync_mode: sync
    sort_title: "!01_RT Latest Certified Fresh"
    collection_mode: hide
    visible_library: false
    visible_home: true
    visible_shared: true
    collection_order: alpha
    build_collection: true
    url_poster: https://github.com/Ramshackles/Plex-Meta-Manager-Images/raw/master/chart/RT%20Latest%20Certified%20Fresh.jpg
    allowed_library_types: movie
    radarr_add_missing: true
    radarr_tag: pmm_rtlatestfresh

  RT Certified Fresh:
    mdblist_list: https://mdblist.com/lists/linaspurinis/certified-fresh
    summary: Certified Fresh releases from Rotten Tomatoes
    sync_mode: sync
    sort_title: "!01_RT Certified Fresh"
    collection_mode: hide
    visible_library: false
    visible_home: true
    visible_shared: true
    collection_order: alpha
    build_collection: true
    url_poster: https://github.com/Ramshackles/Plex-Meta-Manager-Images/raw/master/chart/RT%20Certified%20Fresh.jpg
    allowed_library_types: movie
    # radarr_add_missing: true
    # radarr_tag: pmm_nfmovie